# Python CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-python/ for more details
#
version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.6.1
        environment:
            PIPENV_VENV_IN_PROJECT: true

    steps:
      - checkout
      - run:
          command: |
            sudo pip install pipenv
            pipenv install
            mkdir -p test_results/mamba
      - run:
          name: run tests
          command: |
            pipenv run mamba --format junit > test_results/mamba/results.xml
      - store_test_results:
          path: test_results
